# used to run services
services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./.d–∞ta/redis:/root/redis
#      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PORT=6379
    command: redis-server --bind 0.0.0.0 --port 6379
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 10s
      retries: 3


networks:
  app-network:
    driver: bridge